Models/Basket.cs
using System.ComponentModel.DataAnnotations;

//Created by Adam Sinclair

namespace currentworkingsassyplanner.Models
{
    public class Basket
    {

        [Key]
        public int BasketID { get; set; }

        [Required, MaxLength(32)]
        public string CookieID { get; set; } = string.Empty;



    }
}

Pages/Basket.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using currentworkingsassyplanner.Data;
using currentworkingsassyplanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

//initially made by Alex, mostly rewritten by Sam
namespace currentworkingsassyplanner.Pages
{
    public class BasketModel : PageModel
    {
        private readonly SPContext _spContext;
        private readonly UserManager<IdentityUser> _userManager;

        [BindProperty]
        public bool isLoggedIn { get; set; }

        [BindProperty]
        public List<string> prodName { get; set; }
        [BindProperty]
        public List<decimal> prodPrice { get; set; }

        public IList<BasketItem> Items { get; private set; }
        public decimal Total;
        public long AmountPayable;

        public BasketModel(SPContext spContext, UserManager<IdentityUser> userManager)
        {
            _spContext = spContext;
            _userManager = userManager;
            prodName = new List<string>();
            prodPrice = new List<decimal>();
        }

        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if(user !=null)
            {
                isLoggedIn = true;
                var customer = _spContext.Customers.FromSqlRaw("SELECT * FROM Customer WHERE Email = {0}", user.Email).ToList().FirstOrDefault();

                if (customer != null)
                {

                    Items = await _spContext.BasketItems
                                        .Where(b => b.BasketID == customer.BasketID)
                                        .ToListAsync();


                    if (Items != null && Items.Count > 0)
                    {
                        foreach (var item in Items)
                        {

                            var prod = _spContext.Products.FromSqlRaw("SELECT * FROM Product WHERE ProductID = {0}", item.ProductID).FirstOrDefault();
                            if (prod != null)
                            {
                                prodName.Add(prod.ProductName);
                                Total += (item.Quantity * prod.ProductPrice);
                                prodPrice.Add(item.Quantity * prod.ProductPrice);
                            }
                        }
                    }
                }
            }
            else
            {
                isLoggedIn = false;
            }

            


        }

        public async Task OnPostDeleteAsync(int basketItemID)
        {

            var allItems = _spContext.BasketItems.FromSqlRaw("SELECT * FROM BasketItem WHERE BasketItemID = {0}", basketItemID);
            BasketItem item = new BasketItem();
            if(allItems !=  null)
            {
                item = allItems.FirstOrDefault();
                _spContext.BasketItems.Remove(item);

            }

            //Save the changes, then refresh the basket table.
            await _spContext.SaveChangesAsync();
            //Items = GetCheckoutItems(customer);
            await OnGetAsync();
        }

        //public async Task<IActionResult> OnPostBuyAsync()
        //{
        //    var user = await _userManager.GetUserAsync(User);
        //    if (user != null)
        //    {
        //        var customer = _spContext.Customers.FromSqlRaw("SELECT * FROM Customer WHERE Email = {0}", user.Email).ToList().FirstOrDefault();

        //        if (customer == null)
        //        {
        //            // Handle case where customer is not found
        //            return Page();
        //        }

        //        var order = new CustomerOrder
        //        {
        //            CustomerID = customer.CustomerID,
        //            OrderPrice = Total
        //        };

        //        _spContext.Orders.Add(order);
        //        await _spContext.SaveChangesAsync();

        //        var basketItems = await _spContext.Ba sketItems
        //                                          .Where(b => b.BasketID == customer.BasketID)
        //                                          .ToListAsync();

        //        foreach (var item in basketItems)
        //        {
        //            _spContext.BasketItems.Remove(item);
        //        }

        //        await _spContext.SaveChangesAsync();
        //    }
        //    return RedirectToPage("/OrderConfirmation");
        //}
    }
}

Pages/Contact.cshtml.cs
using currentworkingsassyplanner.Email;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Net.Mail;

namespace currentworkingsassyplanner.Pages
{
    //Made by Adam Sinclair
    public class ContactModel : PageModel
    {

        [BindProperty, Required(ErrorMessage = "Name is required."), RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Name may only contain letters.")]
        public string m_Name { get; set; } = string.Empty;

        [BindProperty, Required(ErrorMessage = "Subject is required.")]
        public string m_Subject { get; set; } = string.Empty;

        [BindProperty, Required(ErrorMessage = "Valid Email is required."), EmailAddress]
        public string m_Email { get; set; } = string.Empty;

        [BindProperty, Required(ErrorMessage = "Message is required.")]
        public string m_Message { get; set; } = string.Empty;

        public string m_SuccessMessage { get; set; } = string.Empty;
        public string m_ErrorMessage { get; set; } = string.Empty;


        public void OnPostSendEmailAsync()
        {
            if(!ModelState.IsValid)
            {
                m_ErrorMessage = "The email was not successfully sent.";
            }
            else
            {
                m_SuccessMessage = "The email was successfully sent.";

                EmailSender sender = new EmailSender();
                sender.SendEmail(m_Name, m_Subject, m_Email, m_Message);
            }


        }

        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace currentworkingsassyplanner.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/FAQ.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace currentworkingsassyplanner.Pages
{
    public class FAQModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shop.cshtml.cs
using currentworkingsassyplanner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace currentworkingsassyplanner.Pages
{
    // Made by Adam Sinclair, edited by Sam Duggan
    public class ShopModel : PageModel
    {
        private readonly currentworkingsassyplanner.Data.SPContext _context;
        public ShopModel(currentworkingsassyplanner.Data.SPContext context)
        {
            _context = context;
        }

        public enum ProductType
        {
            AcademicPlanner, WeeklyLessonPlanner, DailyLessonPlanner, Notebook, Sticker
        }

        public enum Style
        {
            Floral, Animals, Pattern, Landscape, Other
        }

        //Sam's code start
        [BindProperty]
        //Sam's code end
        public List<List<Product>> CategorisedProductTBL { get; set; } = new List<List<Product>>();

        [BindProperty]
        public List<List<Product>> StyleProductTBL { get; set; } = new List<List<Product>>();

        //Sam's code start
        [BindProperty(Name = "FilteredCategories")]
        public string[] FilteredCategories { get; set; }

        [BindProperty(Name = "FilteredStyles")]
        public string[] FilteredStyles { get; set; }


        public bool isFiltered = false;
        //Sam's code end

        public void OnGet()
        {
            
            GetAllProducts();
        }

        public string getTitle(string item)
        {
            string title = "";
            switch (item)
            {
                case "AcademicPlanner":
                    title = "Academic Planners";
                    break;
                case "WeeklyLessonPlanner":
                    title = "Weekly Lesson Planners";
                    break;
                case "DailyLessonPlanner":
                    title = "Daily Lesson Planners";
                    break;
                case "Notebook":
                    title = "Notebooks";
                    break;
                case "Sticker":
                    title = "Stickers";
                    break;
            }
            return title;
        }

        private void GetAllProducts()
        {
            List<List<Product>> categorisedProducts = new List<List<Product>>();
            //List<List<Product>> productsbyStyle = new List<List<Product>>();


            for (int i = 0; i < Enum.GetValues(typeof(ProductType)).Length; i++)
            {
                var productTypeEnums = Enum.GetValues(typeof(ProductType));
                var currentEnum = productTypeEnums.GetValue(i).ToString();
                categorisedProducts.Add(_context.Products.FromSqlRaw("SELECT * FROM Product WHERE ProductType= {0}", currentEnum).ToList());

            }

            List<List<Product>> productsByStyle = new List<List<Product>>();

            for (int i = 0; i < Enum.GetValues(typeof(Style)).Length; i++)
            {
                var styleEnums = Enum.GetValues(typeof(Style));
                var currentEnum = styleEnums.GetValue(i).ToString();
                productsByStyle.Add(_context.Products.FromSqlRaw("SELECT * FROM Product WHERE Style= {0}", currentEnum).ToList());

            }

            CategorisedProductTBL = categorisedProducts;
            StyleProductTBL = productsByStyle;

        }

        /*static void RemoveDuplicates(List<List<Product>> list1, List<List<Product>> list2)
        {
            HashSet<Product> uniqueProducts = new HashSet<Product>();

            // Remove duplicates from list1
            foreach (List<Product> productList in list1)
            {
                foreach (Product product in productList)
                {
                    if (!uniqueProducts.Contains(product))
                    {
                        uniqueProducts.Add(product);
                    }
                }
            }

            // Remove duplicates from list2 and add unique products to uniqueProducts HashSet
            foreach (List<Product> productList in list2)
            {
                foreach (Product product in productList)
                {
                    if (!uniqueProducts.Contains(product))
                    {
                        uniqueProducts.Add(product);
                    }
                }
            }

            // Clear list1 and list2 and add unique products back to them
            list1.Clear();
            list2.Clear();

            foreach (Product product in uniqueProducts)
            {
                list1.Add(new List<Product> { product });
                list2.Add(new List<Product> { product });
            }
        }*/


        public IActionResult OnPostApplyFilter()
        {
            isFiltered = true;
            GetAllProducts();

            string theQuery = string.Empty;

            //If the user wants to filter by category
            if(FilteredCategories.Length > 0)
            {
                //Initial SQL
                theQuery += "SELECT * FROM Product WHERE (ProductType = ";

                //If the user only wants to filter by one category
                if (FilteredCategories.Length == 1)
                {
                    theQuery += $"'{FilteredCategories[0]}' ";
                }
                //If the user wants to filter by multiple
                else if (FilteredCategories.Length > 1)
                {
                    for (int i = 0; i < FilteredCategories.Length; i++)
                    {
                        if (i != FilteredCategories.Length - 1)
                        {
                            theQuery += $"'{FilteredCategories[i]}' OR ProductType = ";

                        }
                        else
                        {
                            theQuery += $"'{FilteredCategories[i]}'";
                        }

                    }
                }


                theQuery += ") ";

                //If the user also wants to filter on style
                if (FilteredStyles.Length > 0)
                {
                    theQuery += " AND (Style = ";

                    if (FilteredStyles.Length == 1)
                    {
                        theQuery += $"'{FilteredStyles[0]}' ";
                    }
                    else if (FilteredStyles.Length > 1)
                    {
                        for (int i = 0; i < FilteredStyles.Length; i++)
                        {
                            if (i != FilteredStyles.Length - 1)
                            {
                                theQuery += $"'{FilteredStyles[i]}' OR Style = ";

                            }
                            else
                            {
                                theQuery += $"'{FilteredStyles[i]}'";
                            }

                        }
                    }

                    theQuery += ")";
                }

            }
            //If the user does not want to filter on category, but on style
            else if(FilteredStyles.Length > 0)
            {
                //Initial SQL query
                theQuery += "SELECT * FROM Product WHERE (Style = ";

                //If the user only wants to filter on one style
                if (FilteredStyles.Length == 1)
                {
                    theQuery += $"'{FilteredStyles[0]}' ";
                }
                //If the user wants to filter on multiple styles
                else if (FilteredStyles.Length > 1)
                {
                    for (int i = 0; i < FilteredStyles.Length; i++)
                    {
                        if (i != FilteredStyles.Length - 1)
                        {
                            theQuery += $"'{FilteredStyles[i]}' OR Style = ";

                        }
                        else
                        {
                            theQuery += $"'{FilteredStyles[i]}'";
                        }

                    }
                }

                theQuery += ")";
            }

            //If the user has pressed apply filter without selecting any, don't do anyhting
            if(theQuery != string.Empty)
            {
                CategorisedProductTBL = new List<List<Product>>();
                CategorisedProductTBL.Add(_context.Products.FromSqlRaw(theQuery).ToList());
            }
            
            return Page();

            /*string mainSqlQuery = "SELECT * FROM Product WHERE (ProductType = ";

            if (FilteredCategories.Length == 1)
            {
                mainSqlQuery += $"'{FilteredCategories[0]}' ";
            }
            else if (FilteredCategories.Length > 1)
            {
                for (int i = 0; i < FilteredCategories.Length; i++)
                {
                    if (i != FilteredCategories.Length - 1)
                    {
                        mainSqlQuery += $"'{FilteredCategories[i]}' OR ProductType = ";

                    }
                    else
                    {
                        mainSqlQuery += $"'{FilteredCategories[i]}'";
                    }

                }
            }

            

            mainSqlQuery += ") ";



            if (FilteredStyles.Length > 0)
            {
                mainSqlQuery += " AND (Style = ";

                if (FilteredStyles.Length == 1)
                {
                    mainSqlQuery += $"'{FilteredStyles[0]}' ";
                }
                else if (FilteredStyles.Length > 1)
                {
                    for (int i = 0; i < FilteredStyles.Length; i++)
                    {
                        if (i != FilteredStyles.Length - 1)
                        {
                            mainSqlQuery += $"'{FilteredStyles[i]}' OR Style = ";

                        }
                        else
                        {

Pages/Basket.cshtml
@page
@model currentworkingsassyplanner.Pages.BasketModel
@{
    ViewData["Title"] = "Sassy Planner Basket";
}
@using currentworkingsassyplanner.Data
@using Microsoft.Extensions.Options

<!--made by Alex, edited by Sam-->

<head>
    <link rel="stylesheet" href="~/css/basket.css" />
</head>

<body class="text-center"> 
    <h1 class="mt-5"> Basket </h1>
    
    @if(Model.isLoggedIn == false)
    {
        <p>Please log in to view your basket</p>
    }
    else if (Model.Items == null || Model.Items.Count == 0) //if Items is null (BasketID doesn't exist), or there are no items in the basket
    {

        <p>Your Basket is empty, or it might not exist.</p>
        <a asp-page="/OrderConfirmation"><button class="link-primary">View Order Conf Page</button></a> //temporary, used to access order confirmation
    }
    else //otherwise display info about items in the basket
    {
        <p>Items in your basket: </p>
    
            
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Personalisation</th>
                            <th>Spiral Colour</th>
                            <th>Start Month</th>
                            <th>Internal Pages</th>
                            <th>Planner Size</th>
                            @* <th>Quantity</th> *@
                            <th>Item Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                @for(int i = 0; i < Model.Items.Count(); i++)
                {
                    <form method="post" asp-page-handler="Delete" asp-route-basketItemID="@Model.Items[i].BasketItemID">

                    <tr>
                        <td>@Model.prodName[i]</td>
                        <td>@Model.Items[i].Personalisation</td>
                        <td>@Model.Items[i].SpiralColour</td>
                        <td>@Model.Items[i].StartMonth</td>
                        <td>@Model.Items[i].InternalPages</td>
                        <td>@Model.Items[i].PlannerSize</td>
                        @* <td>@Model.Items[i].Quantity.ToString()</td> *@
                        <td>@Model.prodPrice[i].ToString("C")</td>
                        <td>
                            <button type="submit"> Delete </button>
                        </td>
                    </tr>
                    </form>
                }
                
                    </tbody>
                </table>

                <h2>Order Total: @Model.Total.ToString("C")</h2>

        <a asp-page="/CheckOut"><button id="button" class="btn py-2 px-3 my-1 fw-bold">Proceed to Checkout</button></a>

    }
</body>

Pages/Contact.cshtml
@page
@model currentworkingsassyplanner.Pages.ContactModel
@{
}

<!-- Made by Adam Sinclair -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HTML5 Boilerplate</title>
    <link rel="stylesheet" href="site.css">
    <link rel="stylesheet" href="~/css/general.css">
    <link rel="stylesheet" href="~/css/contact.css">
</head>

<body>

    <div class="container mb-5">
        <div class="row justify-content-center text-center my-lg-5">
            <h1 id="g-h2-styling">Contact</h1>
        </div>

        <div class="d-flex row">

            <div class="col-sm-6">

                <h3 id="g-h3-styling">Email</h3>
                <form method="post">
                    <div id="g-body-styling text-center">
                        <div class="row my-2">
                            <label class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-7">
                                <input id="g-background-color-only" class="form-control" asp-for="m_Name" />
                                <span asp-validation-for="m_Name" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row my-2">
                            <label class="col-sm-4 col-form-label">Subject</label>
                            <div class="col-sm-7">
                                <input id="g-background-color-only" type="form-control" class="form-control" asp-for="m_Subject" />
                                <span asp-validation-for="m_Subject" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row my-2">
                            <label class="col-sm-4 col-form-label">Email</label>
                            <div class="col-sm-7">
                                <input id="g-background-color-only" type="form-control" class="form-control" asp-for="m_Email" />
                                <span asp-validation-for="m_Email" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row my-2">
                            <label class="col-sm-4 col-form-label">Message</label>
                            <div class="col-sm-7">
                                <textarea id="textarea-contact" class="form-control" asp-for="m_Message"></textarea>
                                <span asp-validation-for="m_Message" class="text-danger"></span>
                            </div>
                        </div>

                        <button id="g-button-style-blue" type="submit" class="d-flex btn my-2 justify-content-end" asp-page-handler="SendEmail">Send Email</button>
                        <!-- id="send-email-button" -->
                    </div>
                </form>
                @if (Model.m_ErrorMessage.Length > 0)
                {
                    <div id="g-body-styling" class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>@Model.m_ErrorMessage</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }
                else if (Model.m_SuccessMessage.Length > 0)
                {
                    <div id="g-body-styling" class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>@Model.m_SuccessMessage</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }
            </div>

            <div class="col-sm-6">
                <h3 id="g-h3-styling">PO Box</h3>
                <p id="g-body-styling">
                    The Sassy Planner Co.
                    <br />
                    Unit 53
                    <br />
                    CoWorkz
                    <br />
                    Minerva Avenue
                    <br />
                    Chester
                    <br />
                    United Kingdom
                    <br />
                    CH1 4QL
                </p>

            </div>

        </div>

    </div>
</body>

    

</html>

Pages/OrderConfirmation.cshtml
@page
@model currentworkingsassyplanner.Pages.OrderConfirmationModel
@{
    ViewData["Title"] = "Order Confirmed!";
}

<head>
    <link rel="stylesheet" href="~/css/orderConfirmation.css" />
</head>

<body>
    <h1>Thank you for your order!</h1>

    @if(Model.OrderInfo == null) //checks if the order info was successfully gathered and if not, displays a different message
    {
        <p>Could not retrieve order info</p>
    }
    else //otherwise displays the details related to the order, similar to a receipt
    {
        @foreach (var info in Model.OrderInfo)
        {
            <p>Order ID: @info.OrderID.ToString("C")</p>
            <p>Order Total: @info.OrderTotal.ToString("C")</p>
            <p>Order Date: @info.OrderDate.ToString("C")</p>
            <p>Delivery address: @info.DeliveryAddress</p>
        }
    }

    <!-- A pair of buttons to allow the user to easily return to the home page or shop page -->
    <p><a asp-page="/Index"><button class="link-primary">Return to homepage</button></a> <a asp-page="/Shop"><button class="link-primary">Keep Shopping</button></a></p>
    
</body>